### ISSUE TITLE
Bad usermod invocation on i2c permissions

### ISSUE THREAD

**Issue by phipolis** [rockowitz/rockowitz.github.io#1]
On the [i2c permissions page](http://www.ddcutil.com/i2c_permissions/), the line 
`# sudo usermod your-user-name -G i2c` should be 
`$ sudo usermod your-user-name -aG i2c` or even
`$ sudo usermod $(whoami) -aG i2c`

Without the -a / --append option, this will overwrite all groups the user is a member of with just i2c. A nasty surprise, especially if they lose wheel/adm and can't sudo any longer!

[Minor, I also changed the # to $, signifying the command is run in the user's shell rather than root]

**Comment by rockowitz** [comment]
Thank you for catching the error.  The web site has been updated.

Sanford

**Comment by fabianski7** [comment]
Following this issue, I believe there is another error on this page: the name of the rules file to be copied is incorrect.

Currently: `45-ddcutils-i2c.rules`
Correct: `45-ddcutil-i2c.rules`
https://github.com/rockowitz/ddcutil/blob/master/data/etc/udev/rules.d/45-ddcutil-i2c.rules

**Comment by rockowitz** [comment]
Thank you for reporting the typo. (It's gratifying to know that some 
people read the documentation!)

The site is actually maintained offline, then uploaded to github.io. so 
I've made the changes there and uploaded.  If you catch any more, just 
send me email at rockowitz@minsoft.com.

**Comment by phipolis** [comment]
Thanks all!
